name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        
    -   name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
     
    - name: Build Astro
      run: pnpm run build

    - name: Upload to Deno Deploy
      uses: denoland/deployctl@v1
        with:
          project: codem8
          entrypoint: server/entry.mjs
          root: dist